# Generated by Django 4.2.23 on 2025-06-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBehavior',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business_intelligence.customerprofile')),
                ('spending_score', models.IntegerField()),
                ('credit_score', models.IntegerField()),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.maritalstatus')),
                ('shopping_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.shoppingfrequency')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingTarget',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business_intelligence.customerprofile')),
                ('target_flag', models.BooleanField()),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.employment')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.income')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.region')),
            ],
        ),
    ]
