# Generated by Django 4.2.23 on 2025-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0002_employment_maritalstatus_shoppingfrequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='annual_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
